### PR TITLE
Build ForgetPassword/ ResetPassword

### PR DESCRIPTION
**Pull request by shivi028**
Refactor ForgetPassword
Remove tailwind.config.js file
Add eye icon in Reset Password
Update toast position to top center

Screenshot 2024-09-15 141135

Screenshot 2024-09-15 141151

### CODE REVIEW

**Comment by Soham-KT** [comment]
change name to "Next Gen Face Authentication"
change icon on forgot password
image

put icon and heading "Next Gen Face Authentication" in reset password
image

remove icon library in index.html

dont use tailwind

remove useless comments from forgotpassword.js

remove console.log

dont use poppin fonts for now

use % instead of pixels

**Comment by nishant0708** [comment]
padding 20 px max ki de

**Comment by nishant0708** [comment]
@shivi028  tailwind css uninstall kar de

**Comment by Soham-KT** [comment]
@shivi028 warning top right corner ki jageh center karde

**Comment by nishant0708** [comment]
forgot password mai bs ek email kai input and  button daal bas !! koi conditon lagaane  ki jarurat nhi hai like verify wagera nhi chahiye just ek "reset password " ka button

**Pull request closed without merging**
